import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import antfu from '@antfu/eslint-config';
import betterTailwindcss from 'eslint-plugin-better-tailwindcss';
import i18nJsonPlugin from 'eslint-plugin-i18n-json';
import reactCompiler from 'eslint-plugin-react-compiler';
import testingLibrary from 'eslint-plugin-testing-library';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Local rule: every feature/lib/ui module must carry a spec.md.
const specRule = require('./scripts/eslint-rule-spec.js');

export default antfu(
  {
    // Enable React and TypeScript support
    react: true,
    // `tsconfigPath` is what turns on antfu/typescript/rules-type-aware —
    // without it the type-aware rule set is registered but never applied, so
    // no-floating-promises and no-misused-promises silently never run.
    typescript: { tsconfigPath: './tsconfig.json' },

    // Disable JSON processing for translation files (handled by i18n-json plugin)
    jsonc: false,

    // Use ESLint Stylistic for formatting
    stylistic: {
      indent: 2,
      quotes: 'single',
      semi: true,
    },

    // Global ignores
    ignores: [
      'dist/*',
      'node_modules',
      '__tests__/',
      'coverage',
      '.expo',
      '.expo-shared',
      'android',
      'ios',
      '.vscode',
      'docs/',
      'cli/',
      'expo-env.d.ts',
      // Generated by uniwind and rewritten on every `pnpm install` and every
      // Metro start, in a shape this config rejects (interfaces, 4-space
      // indent, no semicolons). Its own header says not to edit it by hand, so
      // linting it only ever produces a failure nobody can act on.
      'uniwind-types.d.ts',
      'migration/*',
      // Agent-facing docs: their fenced snippets are illustrative, not code.
      'AGENTS.md',
      'CLAUDE.md',
      'claude.md',
      'agents/**',
      // Vendored agent skills (Argent, tdd). Their fenced snippets are
      // documentation for agents, not code this project compiles or ships.
      '.agents/**',
      '.claude/**',
      // Exported chat transcripts checked in at the repo root.
      'session-*.md',
    ],
  },

  // Custom rules
  {
    rules: {
      'max-params': ['error', 3],
      'max-lines-per-function': ['error', 110],
      'react/display-name': 'off',
      'react/no-inline-styles': 'off',
      'react/destructuring-assignment': 'off',
      'react/require-default-props': 'off',
      'react-refresh/only-export-components': 'warn', // Too strict for React Native
      'unicorn/filename-case': [
        'error',
        {
          case: 'kebabCase',
          ignore: [
            '/android',
            '/ios',
            'README.md',
            'README-project.md',
            'ISSUE_TEMPLATE.md',
            'PULL_REQUEST_TEMPLATE.md',
            'AGENTS.md',
            'ARCHITECTURE.md',
            'CLAUDE.md',
          ],
        },
      ],
      'node/prefer-global/process': 'off', // process is commonly used in React Native configs
      'ts/no-require-imports': 'off', // Sometimes needed for mocks
      'ts/no-use-before-define': 'off', // Allow forward references in React components
      'no-console': 'off', // Console is useful for debugging
      'no-cond-assign': 'off', // Allow assignment in conditions when intentional
      'regexp/no-super-linear-backtracking': 'off', // Relax regex performance rules
      'regexp/no-unused-capturing-group': 'off', // Allow unused capturing groups
    },
  },

  // Type-aware: two adjustments to what antfu turns on.
  //
  // strict-boolean-expressions — antfu allows a nullable boolean and a nullable
  // object in a condition but not a nullable string or number, which fires on
  // every `{label ? <X/> : null}` in the UI kit. The React Native hazard those
  // reports are standing in for is the *other* form, `{label && <X/>}`, which
  // renders a bare '' and crashes with "Text strings must be rendered within a
  // <Text>". That form is caught precisely by react/no-leaked-conditional-
  // rendering, which is also part of this type-aware set and stays on. `allowAny`
  // is deliberately left at its default of false: an `any` reaching a condition
  // means the types were lost upstream, which is worth reporting.
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'ts/strict-boolean-expressions': [
        'error',
        {
          allowNullableBoolean: true,
          allowNullableNumber: true,
          allowNullableObject: true,
          allowNullableString: true,
        },
      ],
      // A `default` clause is how this codebase handles the remainder of a
      // `typeof` switch. Without this option the rule asks for every one of
      // string | bigint | symbol | undefined | object | function to be spelled
      // out beside a default that already covers them.
      'ts/switch-exhaustiveness-check': [
        'error',
        { considerDefaultExhaustiveForUnions: true },
      ],
    },
  },

  // TypeScript-specific rules
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'ts/consistent-type-definitions': ['error', 'type'], // Prefer type over interface
      'react-hooks/refs': 'off', // Allow useRef without exhaustive-deps
      'ts/consistent-type-imports': [
        'warn',
        {
          prefer: 'type-imports',
          fixStyle: 'inline-type-imports',
          disallowTypeAnnotations: true,
        },
      ],
    },
  },

  // Better TailwindCSS plugin
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    ...betterTailwindcss.configs.recommended,
    settings: {
      'better-tailwindcss': {
        entryPoint: path.resolve(__dirname, './src/global.css'),
      },
    },
    rules: {
      ...betterTailwindcss.configs.recommended.rules,
      'better-tailwindcss/no-unnecessary-whitespace': 'warn',
      'better-tailwindcss/no-unknown-classes': 'warn',
      'better-tailwindcss/enforce-consistent-line-wrapping': 'off', // Can be too strict for some cases
    },
  },

  // React Compiler plugin
  {
    plugins: {
      'react-compiler': reactCompiler,
    },
    rules: {
      'react-compiler/react-compiler': 'error',
    },
  },

  // i18n JSON validation
  {
    files: ['src/translations/*.json'],
    plugins: { 'i18n-json': i18nJsonPlugin },
    processor: {
      meta: { name: '.json' },
      ...i18nJsonPlugin.processors['.json'],
    },
    rules: {
      ...i18nJsonPlugin.configs.recommended.rules,
      'i18n-json/valid-message-syntax': [
        2,
        {
          syntax: path.resolve(
            __dirname,
            './scripts/i18next-syntax-validation.js',
          ),
        },
      ],
      'i18n-json/valid-json': 2,
      'i18n-json/sorted-keys': [2, { order: 'asc', indentSpaces: 2 }],
      'i18n-json/identical-keys': [
        2,
        { filePath: path.resolve(__dirname, './src/translations/en.json') },
      ],
      // Disable conflicting rules for i18n JSON files
      'style/semi': 'off',
      'style/comma-dangle': 'off',
      'style/quotes': 'off',
      'unused-imports/no-unused-vars': 'off',
    },
  },

  // Testing Library rules
  {
    files: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)'],
    plugins: { 'testing-library': testingLibrary },
    rules: {
      ...testingLibrary.configs.react.rules,
    },
  },

  // Type-aware rules against test scaffolding.
  //
  // A jest mock has no type by construction: `jest.fn()`, a `require` of an
  // untyped native module, and a partial stub of a third-party surface all
  // produce `any`, so the no-unsafe-* family fires on the act of mocking
  // rather than on a defect. `unbound-method` is the documented false positive
  // for `expect(obj.method)`, and `promise-function-async` is style advice a
  // mock factory has no reason to follow. Turning these off here is what keeps
  // the rules that do find bugs — no-floating-promises, no-misused-promises —
  // readable in the rest of the tree.
  {
    files: [
      '**/__tests__/**/*.[jt]s?(x)',
      '**/?(*.)+(spec|test).[jt]s?(x)',
      '**/__mocks__/**/*.[jt]s?(x)',
      'jest-setup.ts',
    ],
    rules: {
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/promise-function-async': 'off',
      'ts/unbound-method': 'off',
    },
  },

  // Spec drift: features, lib modules and the UI kit must document themselves
  {
    files: [
      'src/features/**/*.{ts,tsx}',
      'src/lib/**/*.{ts,tsx}',
      'src/components/ui/**/*.{ts,tsx}',
    ],
    plugins: { local: { rules: { 'spec-required': specRule } } },
    rules: { 'local/spec-required': 'error' },
  },
);
